<?php

    require_once 'constants/food.php';

    function http_request($url)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        $TOKEN = file_get_contents('private/IBM_TOKEN.txt');

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . $TOKEN);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }
    
    function classifyImage($url)
    {
        $response = http_request('https://api.us-south.visual-recognition.watson.cloud.ibm.com/instances/a1aacfa3-bfa7-4253-9eb8-e34bfaf1fcb3/v3/classify?url=' . $url . '&version=2018-03-19');
        $data = json_decode($response);
        $extraction = $data->images[0]->classifiers[0]->classes;

        global $food;
        $i = 0;
        while($i < count($extraction)) {
            if ($extraction[$i]->class == 'pizza') {
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            elseif ($extraction[$i]->class == 'noodle'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            elseif ($extraction[$i]->class == 'hamburger'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            
            elseif ($extraction[$i]->class == 'sandwich'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            elseif ($extraction[$i]->class == 'stew'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            elseif ($extraction[$i]->class == 'egg'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            elseif ($extraction[$i]->class == 'hotdog'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            elseif ($extraction[$i]->class == 'seafood'){
                $result = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            }
            else {
                $result = "Bukan Makanan";
                $score = $extraction[$i]->score;
            }
            $i++;

            // if (in_array($extraction[$i]->class, $food)) {
            //     $result = $extraction[$i]->class;
            //     $score = $extraction[$i]->score;
            // break;
            // } else {
            //     $result = "Bukan Makanan";
            //     $score = $extraction[$i]->score;
            // }
            // $i++;
        }
    
        $classification = [
            'result'    => $result,
            'score'     => $score
        ];
    
        return (object) $classification;
    }
    