<?php

    require_once $_SERVER['DOCUMENT_ROOT'] . '/Bot-Telegram-IBM-Watson/constants/food.php';

    function http_request($url)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        $TOKEN = file_get_contents('private/IBM_TOKEN.txt');

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . $TOKEN);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }
    
    function classifyImage($url)
    {
        global $food;
        $response = http_request('https://api.us-south.visual-recognition.watson.cloud.ibm.com/instances/a1aacfa3-bfa7-4253-9eb8-e34bfaf1fcb3/v3/classify?url=' . $url . '&version=2018-03-19');
        $data = json_decode($response);
        $extraction = $data->images[0]->classifiers[0]->classes;
    
        $i = 0;
        while($i < count($extraction)) {
            if (in_array($extraction[$i]->class, $food)) {
                $food = $extraction[$i]->class;
                $score = $extraction[$i]->score;
            break;
            } else {
                $food = "Bukan Makanan";
                $score = $extraction[$i]->score;
            }
            $i++;
        }

        $classification = [
            'food'    => $food,
            'score'     => $score
        ];
    
        return (object) $classification;
    }
    